[package]
name = "engctl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
eng-catalog = { path = "../../crates/catalog" }
eng-contracts = { path = "../../crates/contracts" }
serde_json.workspace = true
serde.workspace = true
sha2.workspace = true

[lints]
workspace = true
